name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup pnpm FIRST (before Node)
      # This installs pnpm globally and makes it available in PATH
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false  # We'll run pnpm install manually later

      # Setup Node.js (after pnpm is ready)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install dependencies (monorepo aware)
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Lint (if configured)
      - name: Lint
        run: pnpm lint

      # Typecheck
      - name: Typecheck
        run: pnpm typecheck

      # Test
      - name: Test
        run: pnpm test

      # Build (Turbo)
      - name: Build
        run: pnpm build

      # Check Changesets
      - name: Check Changesets
        run: pnpm changeset status
